const KhyberData = [
{
    img: "../images/img1.jpg",
    id : "#detail1",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img2.jpg",
    id : "#detail2",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img3.jpg",
    id : "detail3",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img3.jpg",
    id : "detail4",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img3.jpg",
    id : "detail1",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img3.jpg",
    id : "detail1",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img3.jpg",
    id : "detail1",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5",
},
{
    img: "../images/img4.jpg",
    id : "#detail1",
    title : "somed title ",
    subtitle : "some sub title",
    advance : "40,000",
    rent : "15,000",
    city: "Khyber",
    location: "Sultan khel",
    type : "village house",
    bids : "3-5"
}
]
export default KhyberData